---
version: "{build}"
branches:
  only:
    - win_build

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundler --version
  - bundle install

  - set PATH=%PATH%;C:\MinGW\bin
build_script:
  - bundle exec rake compile
test_script:
  - bundle exec rake spec

environment:
  matrix:    
    - ruby_version: "22"
    - ruby_version: "22-x64"